# Generated by Django 3.2.13 on 2022-05-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20220501_1909'),
        ('backend', '0015_judgedata'),
    ]

    operations = [
    ]
