# Generated by Django 3.2.13 on 2022-05-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_merge_0009_auto_20220501_1909_0015_judgedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BNNmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128, null=True)),
                ('model_url', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
